
package vlc.ldb.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalDatabase", targetNamespace = "http://soap.ldb.vlc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalDatabase {


    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.ActivityTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateActivity")
    @ResponseWrapper(localName = "createActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/createActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/createActivityResponse")
    public ActivityTO createActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivityTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.ActivityTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadActivity")
    @ResponseWrapper(localName = "readActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/readActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/readActivityResponse")
    public ActivityTO readActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.DoctorTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDoctor", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateDoctor")
    @ResponseWrapper(localName = "createDoctorResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateDoctorResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/createDoctorRequest", output = "http://soap.ldb.vlc/LocalDatabase/createDoctorResponse")
    public DoctorTO createDoctor(
        @WebParam(name = "arg0", targetNamespace = "")
        DoctorTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateActivity")
    @ResponseWrapper(localName = "updateActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateActivityResponse")
    public void updateActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivityTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteActivity")
    @ResponseWrapper(localName = "deleteActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/deleteActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/deleteActivityResponse")
    public void deleteActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<vlc.ldb.soap.ActivityTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listActivities", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListActivities")
    @ResponseWrapper(localName = "listActivitiesResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListActivitiesResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/listActivitiesRequest", output = "http://soap.ldb.vlc/LocalDatabase/listActivitiesResponse")
    public List<ActivityTO> listActivities();

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.AppointmentTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAppointment", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateAppointment")
    @ResponseWrapper(localName = "createAppointmentResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateAppointmentResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/createAppointmentRequest", output = "http://soap.ldb.vlc/LocalDatabase/createAppointmentResponse")
    public AppointmentTO createAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        AppointmentTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.AppointmentTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAppointment", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadAppointment")
    @ResponseWrapper(localName = "readAppointmentResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadAppointmentResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/readAppointmentRequest", output = "http://soap.ldb.vlc/LocalDatabase/readAppointmentResponse")
    public AppointmentTO readAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateAppointment", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateAppointment")
    @ResponseWrapper(localName = "updateAppointmentResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateAppointmentResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateAppointmentRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateAppointmentResponse")
    public void updateAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        AppointmentTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAppointment", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteAppointment")
    @ResponseWrapper(localName = "deleteAppointmentResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteAppointmentResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/deleteAppointmentRequest", output = "http://soap.ldb.vlc/LocalDatabase/deleteAppointmentResponse")
    public void deleteAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<vlc.ldb.soap.AppointmentTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointments", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListAppointments")
    @ResponseWrapper(localName = "listAppointmentsResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListAppointmentsResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/listAppointmentsRequest", output = "http://soap.ldb.vlc/LocalDatabase/listAppointmentsResponse")
    public List<AppointmentTO> listAppointments();

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.DoctorTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readDoctor", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadDoctor")
    @ResponseWrapper(localName = "readDoctorResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadDoctorResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/readDoctorRequest", output = "http://soap.ldb.vlc/LocalDatabase/readDoctorResponse")
    public DoctorTO readDoctor(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateDoctor", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateDoctor")
    @ResponseWrapper(localName = "updateDoctorResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateDoctorResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateDoctorRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateDoctorResponse")
    public void updateDoctor(
        @WebParam(name = "arg0", targetNamespace = "")
        DoctorTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDoctor", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteDoctor")
    @ResponseWrapper(localName = "deleteDoctorResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteDoctorResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/deleteDoctorRequest", output = "http://soap.ldb.vlc/LocalDatabase/deleteDoctorResponse")
    public void deleteDoctor(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<vlc.ldb.soap.DoctorTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDoctors", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListDoctors")
    @ResponseWrapper(localName = "listDoctorsResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListDoctorsResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/listDoctorsRequest", output = "http://soap.ldb.vlc/LocalDatabase/listDoctorsResponse")
    public List<DoctorTO> listDoctors();

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.MeasurementTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMeasurement", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateMeasurement")
    @ResponseWrapper(localName = "createMeasurementResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateMeasurementResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/createMeasurementRequest", output = "http://soap.ldb.vlc/LocalDatabase/createMeasurementResponse")
    public MeasurementTO createMeasurement(
        @WebParam(name = "arg0", targetNamespace = "")
        MeasurementTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.MeasurementTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readMeasurement", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadMeasurement")
    @ResponseWrapper(localName = "readMeasurementResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadMeasurementResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/readMeasurementRequest", output = "http://soap.ldb.vlc/LocalDatabase/readMeasurementResponse")
    public MeasurementTO readMeasurement(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateMeasurement", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateMeasurement")
    @ResponseWrapper(localName = "updateMeasurementResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateMeasurementResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateMeasurementRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateMeasurementResponse")
    public void updateMeasurement(
        @WebParam(name = "arg0", targetNamespace = "")
        MeasurementTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMeasurement", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteMeasurement")
    @ResponseWrapper(localName = "deleteMeasurementResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteMeasurementResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/deleteMeasurementRequest", output = "http://soap.ldb.vlc/LocalDatabase/deleteMeasurementResponse")
    public void deleteMeasurement(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<vlc.ldb.soap.MeasurementTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMeasurements", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListMeasurements")
    @ResponseWrapper(localName = "listMeasurementsResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListMeasurementsResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/listMeasurementsRequest", output = "http://soap.ldb.vlc/LocalDatabase/listMeasurementsResponse")
    public List<MeasurementTO> listMeasurements();

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.UserActivityTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUserActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateUserActivity")
    @ResponseWrapper(localName = "createUserActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateUserActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/createUserActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/createUserActivityResponse")
    public UserActivityTO createUserActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        UserActivityTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.UserActivityTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readUserActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadUserActivity")
    @ResponseWrapper(localName = "readUserActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadUserActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/readUserActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/readUserActivityResponse")
    public UserActivityTO readUserActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateUserActivity")
    @ResponseWrapper(localName = "updateUserActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateUserActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateUserActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateUserActivityResponse")
    public void updateUserActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        UserActivityTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserActivity", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteUserActivity")
    @ResponseWrapper(localName = "deleteUserActivityResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteUserActivityResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/deleteUserActivityRequest", output = "http://soap.ldb.vlc/LocalDatabase/deleteUserActivityResponse")
    public void deleteUserActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<vlc.ldb.soap.UserActivityTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUserActivities", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListUserActivities")
    @ResponseWrapper(localName = "listUserActivitiesResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListUserActivitiesResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/listUserActivitiesRequest", output = "http://soap.ldb.vlc/LocalDatabase/listUserActivitiesResponse")
    public List<UserActivityTO> listUserActivities();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserActivityValue", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateUserActivityValue")
    @ResponseWrapper(localName = "updateUserActivityValueResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateUserActivityValueResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateUserActivityValueRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateUserActivityValueResponse")
    public void updateUserActivityValue(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.UserTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.CreateUserResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/createUserRequest", output = "http://soap.ldb.vlc/LocalDatabase/createUserResponse")
    public UserTO createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserTO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.UserTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readUser", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadUser")
    @ResponseWrapper(localName = "readUserResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ReadUserResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/readUserRequest", output = "http://soap.ldb.vlc/LocalDatabase/readUserResponse")
    public UserTO readUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.UpdateUserResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/updateUserRequest", output = "http://soap.ldb.vlc/LocalDatabase/updateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserTO arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.DeleteUserResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/deleteUserRequest", output = "http://soap.ldb.vlc/LocalDatabase/deleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<vlc.ldb.soap.UserTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsers", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListUsers")
    @ResponseWrapper(localName = "listUsersResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ListUsersResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/listUsersRequest", output = "http://soap.ldb.vlc/LocalDatabase/listUsersResponse")
    public List<UserTO> listUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns vlc.ldb.soap.UserTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByTelegramId", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.GetUserByTelegramId")
    @ResponseWrapper(localName = "getUserByTelegramIdResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.GetUserByTelegramIdResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/getUserByTelegramIdRequest", output = "http://soap.ldb.vlc/LocalDatabase/getUserByTelegramIdResponse")
    public UserTO getUserByTelegramId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "resetDB", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ResetDB")
    @ResponseWrapper(localName = "resetDBResponse", targetNamespace = "http://soap.ldb.vlc/", className = "vlc.ldb.soap.ResetDBResponse")
    @Action(input = "http://soap.ldb.vlc/LocalDatabase/resetDBRequest", output = "http://soap.ldb.vlc/LocalDatabase/resetDBResponse")
    public void resetDB();

}
