
package vlc.ldb.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocalDatabaseService", targetNamespace = "http://soap.ldb.vlc/", wsdlLocation = "https://vlc-server-local-database.herokuapp.com/ws/ldb?wsdl")
public class LocalDatabaseService
    extends Service
{

    private final static URL LOCALDATABASESERVICE_WSDL_LOCATION;
    private final static WebServiceException LOCALDATABASESERVICE_EXCEPTION;
    private final static QName LOCALDATABASESERVICE_QNAME = new QName("http://soap.ldb.vlc/", "LocalDatabaseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://vlc-server-local-database.herokuapp.com/ws/ldb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCALDATABASESERVICE_WSDL_LOCATION = url;
        LOCALDATABASESERVICE_EXCEPTION = e;
    }

    public LocalDatabaseService() {
        super(__getWsdlLocation(), LOCALDATABASESERVICE_QNAME);
    }

    public LocalDatabaseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCALDATABASESERVICE_QNAME, features);
    }

    public LocalDatabaseService(URL wsdlLocation) {
        super(wsdlLocation, LOCALDATABASESERVICE_QNAME);
    }

    public LocalDatabaseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCALDATABASESERVICE_QNAME, features);
    }

    public LocalDatabaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocalDatabaseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalDatabase
     */
    @WebEndpoint(name = "LocalDatabaseImplPort")
    public LocalDatabase getLocalDatabaseImplPort() {
        return super.getPort(new QName("http://soap.ldb.vlc/", "LocalDatabaseImplPort"), LocalDatabase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalDatabase
     */
    @WebEndpoint(name = "LocalDatabaseImplPort")
    public LocalDatabase getLocalDatabaseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ldb.vlc/", "LocalDatabaseImplPort"), LocalDatabase.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCALDATABASESERVICE_EXCEPTION!= null) {
            throw LOCALDATABASESERVICE_EXCEPTION;
        }
        return LOCALDATABASESERVICE_WSDL_LOCATION;
    }

}
